version: '3.3'
services:
  postgres:
    container_name: diag_lab_database
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=diag_lab
  