apiVersion: v1
kind: Service
metadata:
  name: diagnostic-laboratory
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: diagnostic-laboratory
  type: ClusterIP
